[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
fs_permissions = [
  { access = "read", path = "../shared" },
  { access = "write", path = "../shared/deployments" },
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./test/fixtures" },
]

[fuzz]
runs = 1000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "http://127.0.0.1:8545"

[lint]
lint_on_build = false
