// Writes src/components/site/logos.ts: the monochrome marks of the stack clim runs on, from
// @web3icons/core (MIT, dev dependency), recoloured to currentColor so the page's tokens drive them.
// Run: node scripts/make-logos.mjs
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);
const root = require.resolve("@web3icons/core").replace(/index\.js$/, "svgs/");
const SOURCES = {
  Ethereum: "networks/mono/ethereum",
  Chainlink: "tokens/mono/LINK",
  Uniswap: "exchanges/mono/uniswap",
  Coinbase: "exchanges/mono/coinbase",
  Binance: "exchanges/mono/binance",
  Kraken: "exchanges/mono/kraken",
};

const out = {};
for (const [name, file] of Object.entries(SOURCES)) {
  const svg = (await import(pathToFileURL(`${root}${file}.svg.js`).href)).default;
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  const body = svg
    .replace(/^<svg[^>]*>/, "")
    .replace(/<\/svg>$/, "")
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .replace(/\s+/g, " ")
    .trim();
  out[name] = { viewBox, body };
}

writeFileSync(
  new URL("../src/components/site/logos.ts", import.meta.url),
  `// Generated by scripts/make-logos.mjs from @web3icons/core, Copyright (c) 2024 0xa3k5, MIT License (see THIRD_PARTY_NOTICES.md). Do not edit.\nexport const LOGOS: Record<string, { viewBox: string; body: string }> = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`logos.ts: ${Object.keys(out).join(", ")}`);
