// Copies the repo's single sources of truth into the app so the app builds on its own (Vercel
// deploys only app/). Real files only; a missing file fails the sync. Run: npm run sync
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const LAB_FILES = ["summary.json", "replay-2026-02-04.json", "ptrade-band.json", "fables-storm-2026-10-07.json"];

/**
 * /lab's main-scenario sentence needs ETH's own gain (the README's "+0.39% a year"), which the lab's
 * summary.json leaves out: it is backtest-summary.json's yearAttribution for the chosen policy
 * (clim_p<P* in %>), in bp a year. Adds it to the summary as lpGain.mainScenarioEthPctPerYear (in % a
 * year) unless the summary already has it; returns the summary unchanged when the backtest lacks it.
 */
export function withMainScenarioGain(summary, backtest) {
  if (!summary?.lpGain || summary.lpGain.mainScenarioEthPctPerYear !== undefined) return summary;
  const pStar = summary.setting?.pStar;
  const bp = typeof pStar === "number" ? backtest?.yearAttribution?.[`clim_p${Math.round(pStar * 100)}`]?.gainVsStatic5BpYr : undefined;
  if (typeof bp !== "number") return summary;
  return { ...summary, lpGain: { ...summary.lpGain, mainScenarioEthPctPerYear: bp / 100 } };
}

export function syncData({ repoRoot, appRoot }) {
  const report = [];
  const need = (real) => {
    if (!existsSync(real)) throw new Error(`missing ${real}: the app ships real data only`);
    return real;
  };
  const copy = (real, dest) => {
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(need(real), dest);
    report.push({ file: dest.slice(appRoot.length + 1), source: "repo" });
  };
  copy(join(repoRoot, "shared/deployments/sepolia.json"), join(appRoot, "src/generated/sepolia.json"));
  copy(join(repoRoot, "shared/params.json"), join(appRoot, "src/generated/params.json"));
  for (const f of LAB_FILES) copy(join(repoRoot, "lab/out", f), join(appRoot, "public/data/lab", f));
  const backtest = join(repoRoot, "lab/out/backtest-summary.json");
  const summaryOut = join(appRoot, "public/data/lab/summary.json");
  if (existsSync(backtest)) {
    const summary = JSON.parse(readFileSync(summaryOut, "utf8"));
    const merged = withMainScenarioGain(summary, JSON.parse(readFileSync(backtest, "utf8")));
    if (merged !== summary) writeFileSync(summaryOut, `${JSON.stringify(merged, null, 2)}\n`);
  }

  const faq = need(join(repoRoot, "docs/faq.md"));
  const faqOut = join(appRoot, "src/generated/faq.ts");
  writeFileSync(faqOut, `// Generated by scripts/sync-data.mjs from docs/faq.md. Do not edit.\nexport const FAQ_MD = ${JSON.stringify(readFileSync(faq, "utf8"))};\n`);
  report.push({ file: "src/generated/faq.ts", source: "repo" });
  return report;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const appRoot = dirname(dirname(fileURLToPath(import.meta.url)));
  // The repo root is the parent of app/; CLIM_ROOT overrides it.
  const repoRoot = process.env.CLIM_ROOT ? resolve(process.env.CLIM_ROOT) : dirname(appRoot);
  console.table(syncData({ repoRoot, appRoot }));
}
