// Copies the repo's single sources of truth into the app so the app builds on its own (Vercel
// deploys only app/). Real files win; fixtures fill the gaps. Run: npm run sync
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const LAB_FILES = ["summary.json", "replay-2026-02-04.json", "ptrade-band.json"];

export function syncData({ repoRoot, appRoot }) {
  const report = [];
  const pick = (real, fixture) => (existsSync(real) ? { from: real, fixture: false } : { from: fixture, fixture: true });
  const copy = (real, fixture, dest) => {
    const src = pick(real, fixture);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(src.from, dest);
    report.push({ file: dest.slice(appRoot.length + 1), source: src.fixture ? "fixture" : "repo" });
  };
  const fx = join(appRoot, "src/fixtures");
  copy(join(repoRoot, "shared/deployments/sepolia.json"), join(fx, "deployments.sepolia.json"), join(appRoot, "src/generated/sepolia.json"));
  copy(join(repoRoot, "shared/params.json"), join(fx, "params.json"), join(appRoot, "src/generated/params.json"));
  for (const f of LAB_FILES) copy(join(repoRoot, "lab/out", f), join(fx, "lab", f), join(appRoot, "public/data/lab", f));

  const faq = pick(join(repoRoot, "docs/faq.md"), join(fx, "faq.md"));
  const faqOut = join(appRoot, "src/generated/faq.ts");
  writeFileSync(faqOut, `// Generated by scripts/sync-data.mjs from ${faq.fixture ? "src/fixtures/faq.md" : "docs/faq.md"}. Do not edit.\nexport const FAQ_MD = ${JSON.stringify(readFileSync(faq.from, "utf8"))};\n`);
  report.push({ file: "src/generated/faq.ts", source: faq.fixture ? "fixture" : "repo" });
  return report;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const appRoot = dirname(dirname(fileURLToPath(import.meta.url)));
  // The repo root is the parent of app/; CLIM_ROOT overrides it.
  const repoRoot = process.env.CLIM_ROOT ? resolve(process.env.CLIM_ROOT) : dirname(appRoot);
  console.table(syncData({ repoRoot, appRoot }));
}
